### ISSUE TITLE
PIMELauncher.exe blocked by Windows Defender

### ISSUE THREAD

**Issue by Prcuvu** [EasyIME/PIME#149]
According to [the reference] (http://msdn.microsoft.com/en-us/library/windows/apps/hh967425.aspx), it is likely because the executable is not signed.

**Comment by callinner** [comment]
今天Windows Defender偵測到木馬
![2016-07-22_002000](https://cloud.githubusercontent.com/assets/20582557/17030446/0cdffdd2-4fa2-11e6-8e1b-843a797da7c7.png)

**Comment by PCMan** [comment]
剛剛已經發信去微軟抗議了，希望可以得到善意回應:
https://www.microsoft.com/en-us/security/portal/mmpc/developer/resources.aspx

**Comment by PCMan** [comment]
懷疑有可能跟外界網路有可能連進 libpipe.dll 有關
根據 API doc, Windows named pipe 似乎可以穿透網路
https://msdn.microsoft.com/zh-tw/library/windows/desktop/aa365590(v=vs.85).aspx
"Named pipes can be used to provide communication between processes on the same computer or between processes on different computers across a network. If the server service is running, all named pipes are accessible remotely. If you intend to use a named pipe locally only, deny access to NT AUTHORITY\NETWORK or switch to local RPC."
要讓他只有 local 可以連線，需要阻斷 AUTHORITY\network 的 ACCESS
此 SID 似乎可從這裡取得:
https://msdn.microsoft.com/zh-tw/library/windows/desktop/aa379649(v=vs.85).aspx
SECURITY_NT_AUTHORITY, SECURITY_NETWORK_RID
一邊等待微軟回應，一邊或許可研究這塊

**Comment by KenLuoTW** [comment]
昨天有被 WD 偵測到,今天還沒有出現過警告。

偵測到之後不僅隔離了 PIMELauncher.exe,很多相關檔案都自動消失,
所以須要重新安裝 PIME 才能正常使用。

**Comment by PCMan** [comment]
收到 Microsoft Malware Detection Center 的回覆，表示已經修正，剛測試最新的 WD 已經不會誤判了，請各位協助確認，若沒問題就關閉這個 issue。
附上 Microsoft 的回信：
Microsoft Malware Protection Center <mpcreply@microsoft.com>
Jul 25

to me 
New definition library for Microsoft Anti-Malware has been updated. We believe this new definition library contains the updates necessary to resolve your question in regards to Microsoft Anti-Malware.
 
New definition library is now available for users who subscribe to the automatic definition update mechanism, as well as users who choose to manually update their definition library.
 
We encourage you to try these new definitions and ensure your inquiry has been resolved.  If your machine has not been updated with this version of definitions you can download and install the definitions manually following these steps:
 
• Go to http://www.microsoft.com/security/portal/definitions/adl.aspx
• Download the corresponding definitions (32 bit or 64 bit based on your operating system)
• Run the downloaded file to install the new definitions
 
In case of any further incorrect detections, we ask that you to submit the actual file sample that is detected by the Microsoft Anti-Malware solutions and mark it as an Incorrect Detection (select option “I believe this file should not be detected as malware”). Please make sure you provide your email account details when submitting samples in order to ensure submission communication is complete.

You can use our portal submission form when submitting samples for further investigation available here:
https://www.microsoft.com/security/portal/submission/submit.aspx

 
We apologize for any inconvenience this may have caused.  If you have any additional questions related to this inquiry, please contact us at mpcreply@microsoft.com.  Should you need to contact us in the future regarding a question unrelated to this inquiry, please fill out the appropriate form at  http://www.microsoft.com/security/portal/mmpc/vendor/resources.aspx .
 
Thank you for contacting Microsoft.
 
Sincerely,
Microsoft Malware Protection Center

**Comment by PCMan** [comment]
@Prcuvu , @callinner , @callinner , @KenLuoTW  請協助確認，感謝！

**Comment by KenLuoTW** [comment]
已測試過，重新安裝及直接掃描檔案都沒有出現問題。

**Comment by Prcuvu** [comment]
Fixed.
